Add Codeowner + CI checks (#2)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,30 +2,45 @@ name: Test
 
 on:
   push:
+    branches: [master]
   pull_request:
+    branches: [master]
 
 jobs:
-  test:
+  matrix-test:
     runs-on: ubuntu-latest
 
     strategy:
       fail-fast: false
       matrix:
-        ruby: [ '3.0', '3.1', '3.2', '3.3' ]
-        rails: [ '6.1', '7.0', '7.1' ]
+        ruby: ['3.2', '3.3', '3.4']
 
-    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
-    env:
-      BUNDLE_GEMFILE: gemfiles/Gemfile-activemodel-${{ matrix.rails }}.x
+    name: Ruby ${{ matrix.ruby }}
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-    - name: Setup Ruby
-      uses: ruby/setup-ruby@v1
-      with:
-        ruby-version: ${{ matrix.ruby }}
-        bundler-cache: true # 'bundle install' and cache gems
+      - name: Setup Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby }}
+          bundler-cache: true
 
-    - name: RSpec
-      run: bundle exec rake
+      - name: RSpec
+        run: bundle exec rake
+
+  test:
+    needs: matrix-test
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check status
+        run: |
+          RESULT="${{ needs.matrix-test.result }}"
+          if [ "$RESULT" == "success" ] || [ "$RESULT" == "skipped" ]; then
+            echo "All required tests passed!"
+            exit 0
+          else
+            echo "Required tests failed."
+            exit 1
+          fi
